require("config.lazy")
require("config.colorscheme")
require("config.alpha")
require("config.lualine")
require("config.autopairs")
require("config.neotree")
require("config.options")
require("config.keymaps")
